# -*- coding: utf-8 -*-
"""Customer_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuexV3y7BXQqpGanUmsrkxcr_4EBBFV4
"""

#Import the required libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

#Sample data : Annual Income in $1000s, Spending Score)
#This simulates the basic behaviour
x = np.array([
    # Low income, High spending (20 customers)
    [20,80],[22,85],[18,78],[25,82],[21,79],
    [19,83],[23,81],[24,77],[17,86],[26,80],
    [20,75],[22,88],[18,82],[25,79],[21,83],
    [19,77],[23,85],[24,80],[17,78],[26,82],

    # High income, Low spending (20 customers)
    [85,20],[88,22],[82,18],[90,25],[86,21],
    [84,19],[87,23],[89,24],[83,17],[91,26],
    [85,15],[88,22],[82,18],[90,25],[86,21],
    [84,19],[87,23],[89,24],[83,17],[91,26],

    # High income, High spending (20 customers)
    [85,80],[88,82],[82,78],[90,85],[86,81],
    [84,79],[87,83],[89,84],[83,77],[91,86],
    [85,80],[88,82],[82,78],[90,85],[86,81],
    [84,79],[87,83],[89,84],[83,77],[91,86],
])

inertia=[]
k_range=range(1,11)
for k in k_range:
  kmeans=KMeans(n_clusters=k,random_state=42)
  kmeans.fit(x)
  inertia.append(kmeans.inertia_)
#plot of k_range and inertia
plt.plot(k_range,inertia,marker='o',color='black')
plt.xlabel("krange")
plt.ylabel("inertia")
plt.title('Elbow Method')
plt.grid(True)
plt.show()

#Create K-Means Model with K=3
kmeans=KMeans(n_clusters=3,random_state=42)

#Fit the model and find clusters
y_kmeans=kmeans.fit_predict(x)

#Get cluster center
centers=kmeans.cluster_centers_

#Plot the clusters with different colors
plt.figure(figsize=(8,6))
plt.scatter(x[:,0],x[:,1],c=y_kmeans,cmap='viridis',label='Customers')
plt.scatter(centers[:,0],centers[:,1],c='red',s=200,marker='o',label='Centroids')
plt.xlabel('Annual Income in $1000s')
plt.ylabel('Spending Score')
plt.title('Customer Segmentation using K-means Clustering')
plt.legend()
plt.grid(True)
plt.show()

#Display the final cluster centers
print("Cluster Centers (Annual Income,Spending Score):")
for i , center in enumerate (centers):
  print(f"Cluster{i+1}:Income ={center[0]:.2f},Spending Score ={center[1]:.2f}")